"""empty message

Revision ID: 22edfd1c9f45
Revises: f422af69bda7
Create Date: 2018-04-13 23:43:18.901000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22edfd1c9f45'
down_revision = 'f422af69bda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('killmails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('solar_system', sa.BIGINT(), nullable=True),
    sa.Column('killmail_time', sa.String(length=200, convert_unicode=True), nullable=True),
    sa.Column('attackers', sa.String(), nullable=True),
    sa.Column('zkb', sa.String(), nullable=True),
    sa.Column('victim', sa.String(), nullable=True),
    sa.Column('killmail_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'contact', sa.Column('character_contact_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'contact', 'character_contact_id')
    op.drop_table('killmails')
    # ### end Alembic commands ###