"""empty message

Revision ID: 2e2ed612d45a
Revises: 22edfd1c9f45
Create Date: 2018-04-14 13:46:43.257000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2ed612d45a'
down_revision = '22edfd1c9f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('killmails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('solar_system', sa.BIGINT(), nullable=True),
    sa.Column('killmail_time', sa.String(length=20000, convert_unicode=True), nullable=True),
    sa.Column('attackers', sa.String(length=20000), nullable=True),
    sa.Column('zkb', sa.String(length=20000), nullable=True),
    sa.Column('victim', sa.String(length=20000), nullable=True),
    sa.Column('killmail_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('killmails')
    # ### end Alembic commands ###