"""empty message

Revision ID: f422af69bda7
Revises: fab636b98bc7
Create Date: 2018-04-13 13:39:09.436000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f422af69bda7'
down_revision = 'fab636b98bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('character_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('character_contact_standing', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.add_column(u'user', sa.Column('character_contacts_id', sa.String(length=20000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'character_contacts_id')
    op.drop_table('contact')
    # ### end Alembic commands ###